### ISSUE TITLE
Замечания по второму заданию

### ISSUE THREAD

**Issue by gf2crypto** [Kasaderos/crypto_python#2]
1. Константу EPS, видимо, нужно удалить. Она нигде не используется.

2. Реализовать разбор аргументов командной строки средствами библиотеки argparse.

3. Режим -d должен реализовать обычное расшифрование, а не взлом.

4. Взлом должен выполняться в два этапа: должен быть режим построения модели по файлам, и второй режим - взлом ключа по с помощью модели. Таким образом, эти режимы должны присутствовать в командной строке.

**Comment by Kasaderos** [comment]
1. Убрал eps
2. Реализовал через argparse
3. -d теперь делает то что надо
4. сделано
Калдаров Б.М. 416
